-- Banco do Magnobag no Supabase (PostgreSQL). O site conecta direto pelo DATABASE_URL.
-- RLS ligado e sem políticas: a API pública do Supabase (chave anon) não enxerga nada destas tabelas.

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  senha_hash text not null,
  premium integer not null default 0,
  criado_em timestamptz not null default now()
);

create table if not exists public.favoritos (
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  ticker text not null,
  criado_em timestamptz not null default clock_timestamp(),  -- mantém a ordem em que foram adicionados
  primary key (usuario_id, ticker)
);

alter table public.usuarios enable row level security;
alter table public.favoritos enable row level security;

-- arquivos privados do site (ex.: imagem do mascote do dono), entregues só pelo próprio site
create table if not exists public.arquivos (
  nome text primary key,
  tipo text not null,
  dados bytea not null
);
alter table public.arquivos enable row level security;

-- nome amigável do ativo, guardado quando ele é adicionado pela busca
alter table public.favoritos add column if not exists nome text;
